import type { After, Customer, Deal, Progress } from "@/lib/crm-types";

export const customers: Customer[] = [
  {
    id: "c001",
    name: "田中 一郎",
    company: "田中邸（個人）",
    phone: "090-1234-5678",
    email: "tanaka@example.com",
    address: "東京都世田谷区",
  },
  {
    id: "c002",
    name: "佐藤 美咲",
    company: "佐藤マンション管理組合",
    phone: "03-5555-1234",
    email: "sato-mgmt@example.com",
    address: "神奈川県横浜市",
  },
  {
    id: "c003",
    name: "鈴木 健太",
    company: "鈴木工務店",
    phone: "045-777-8899",
    email: "suzuki@koumuten.example.com",
    address: "神奈川県川崎市",
  },
  {
    id: "c004",
    name: "高橋 由美",
    company: "高橋邸（個人）",
    phone: "080-9876-5432",
    email: "takahashi@example.com",
    address: "東京都調布市",
  },
];

export const deals: Deal[] = [
  {
    id: "d001",
    customerId: "c001",
    date: "2026-05-20",
    summary: "外壁塗装の見積依頼。築15年、色褪せと細かいクラックを確認。",
    status: "見積中",
  },
  {
    id: "d002",
    customerId: "c001",
    date: "2026-05-22",
    summary: "下見結果を共有。シリコン系2回塗りを提案、予算感は350万円前後。",
    status: "フォロー中",
    progressId: "p001",
  },
  {
    id: "d003",
    customerId: "c002",
    date: "2026-04-10",
    summary: "共用部塗装の入札説明会に参加。工期3ヶ月を希望。",
    status: "契約済",
    progressId: "p002",
  },
  {
    id: "d004",
    customerId: "c003",
    date: "2026-05-18",
    summary: "新築外壁の下請け相談。月2件程度の継続案件を想定。",
    status: "フォロー中",
  },
  {
    id: "d005",
    customerId: "c003",
    date: "2026-05-24",
    summary: "単価表と品質基準書の共有を依頼。来週打ち合わせ予定。",
    status: "見積中",
    progressId: "p004",
  },
  {
    id: "d006",
    customerId: "c004",
    date: "2026-02-28",
    summary: "屋根・外壁同時施工で契約。梅雨前完工を希望。",
    status: "契約済",
    progressId: "p005",
  },
];

export const progresses: Progress[] = [
  {
    id: "p001",
    customerId: "c001",
    dealId: "d002",
    propertyName: "田中邸 外壁塗装",
    phase: "見積・下見",
    percentComplete: 30,
    nextAction: "5/28 見積書提出",
  },
  {
    id: "p002",
    customerId: "c002",
    dealId: "d003",
    propertyName: "佐藤マンション 共用部",
    phase: "足場組立",
    percentComplete: 55,
    nextAction: "6/2 中間報告会",
  },
  {
    id: "p003",
    customerId: "c002",
    dealId: "d003",
    propertyName: "佐藤マンション 屋上防水",
    phase: "下地処理",
    percentComplete: 40,
    nextAction: "6/5 防水施工開始",
  },
  {
    id: "p004",
    customerId: "c003",
    dealId: "d005",
    propertyName: "川崎市A区画 新築3棟",
    phase: "契約準備",
    percentComplete: 10,
    nextAction: "6/1 単価表送付",
  },
  {
    id: "p005",
    customerId: "c004",
    dealId: "d006",
    propertyName: "高橋邸 屋根・外壁",
    phase: "完工・引渡し",
    percentComplete: 100,
    nextAction: "5/30 最終報告書提出",
  },
  {
    id: "p006",
    customerId: "c003",
    propertyName: "川崎市B区画 外壁（2025年施工）",
    phase: "保証期間中",
    percentComplete: 100,
    nextAction: "次回定期点検：2026-09",
  },
];

export const afters: After[] = [
  {
    id: "a001",
    customerId: "c002",
    progressId: "p002",
    date: "2026-05-15",
    type: "苦情対応",
    note: "近隣からの騒音問い合わせ。作業時間帯を調整し、告知文を再配布済み。",
    status: "完了",
  },
  {
    id: "a002",
    customerId: "c003",
    progressId: "p006",
    date: "2026-03-10",
    type: "定期点検",
    note: "前回施工物件の1年点検。問題なし。",
    status: "完了",
  },
  {
    id: "a003",
    customerId: "c004",
    progressId: "p005",
    date: "2026-05-26",
    type: "アフター点検",
    note: "引渡し後1ヶ月点検予定。雨漏り確認を実施。",
    status: "予定",
  },
  {
    id: "a004",
    customerId: "c004",
    progressId: "p005",
    date: "2025-12-01",
    type: "定期点検",
    note: "施工完了時の最終確認。保証書交付済み。",
    status: "完了",
  },
];
